DROP DATABASE IF EXISTS employees_DB;

CREATE DATABASE employees_DB;

USE employees_DB;

/* DPT TABLE */
CREATE TABLE DEPARTMENT (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100),
    PRIMARY KEY (ID)
);

/* ROLE TABLE */
CREATE TABLE ROLES (
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(100),
    SALARY DECIMAL,
    DEPARTMENT_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_department FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)

);
/* EMPLOYEE TABLE */
CREATE TABLE EMPLOYEES (
    ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    ROLE_ID INT NOT NULL,
    MANAGER KEY (ID),
    PRIMARY KEY (ID),
    CONSTRAINT fk_role FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),
    CONSTRAINT fk_role FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (ID),
);